# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mutantdetector

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mutantdetectorapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8f1be4ee23294cb8afd19f19d6583252 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63c56ce404564113845ce48f361bdbe1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_8f1be4ee23294cb8afd19f19d6583252 }}/mutantdetectorapi:${{ github.sha }}
        file: ./MutantDetector.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mutantdetector'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dca90376761c469abe259a47e8cf41cc }}
        images: 'mutantdetectorapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f1be4ee23294cb8afd19f19d6583252 }}/mutantdetectorapi:${{ github.sha }}'
